name: mono-ci
on: [push]
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-1-step-1
      - run: npm test -- --shard=1/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-2-step-1
      - run: npm test -- --shard=2/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-3-step-1
      - run: npm test -- --shard=3/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_4:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-4-step-1
      - run: npm test -- --shard=4/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-5-step-1
      - run: npm test -- --shard=5/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-6-step-1
      - run: npm test -- --shard=6/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-7-step-1
      - run: npm test -- --shard=7/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-8-step-1
      - run: npm test -- --shard=8/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-9-step-1
      - run: npm test -- --shard=9/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_10:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-10-step-1
      - run: npm test -- --shard=10/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-11-step-1
      - run: npm test -- --shard=11/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
  job_12:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo job-12-step-1
      - run: npm test -- --shard=12/12
      - run: echo 'padding-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'